Cargo.toml
src/app.rs
src/app_context.rs
src/config/worker.rs
src/controller/health.rs
src/worker/app_worker.rs
src/worker/registry.rs

Problem
-------
If the job queue is empty, sidekiq.rs will wait a couple seconds before releasing its connection. This can delay adding items to the queue by up to a couple seconds depending on how the timing works out, which is bad because adding the the queue should be as fast as possible.
Solution
--------
Use separate connection pools for enqueuing vs fetching jobs from the queue. This decouples enqueuing from needing to wait for a connection that is being blocked by a worker task that's waiting for a job to be added to the queue in the `sidekiq::Processor`.

Use a separate redis connection pool for enqueuing vs fetching jobs

---

.github/workflows/ci.yml
src/app.rs
src/app_context.rs
src/controller/health.rs
src/worker/mod.rs

Don't run the `sidekiq::Processor` if:
- The app has configured a max connection pool size of zero for the fetch pool
- The app does not have any sidekiq queues configured
https://github.com/roadster-rs/roadster/issues/55

Don't run Processor depending on configs

---

examples/minimal/config/default.toml
examples/minimal/src/app.rs
src/app.rs
src/app_context.rs
src/cli/list_routes.rs
src/cli/mod.rs
src/cli/open_api_schema.rs
src/config/app_config.rs
src/config/mod.rs
src/config/service/http_service/initializer.rs
src/config/service/http_service/middleware.rs
src/config/service/http_service/mod.rs
src/config/service/mod.rs
src/controller/middleware/catch_panic.rs
src/controller/middleware/compression.rs
src/controller/middleware/request_id.rs
src/controller/middleware/sensitive_headers.rs
src/controller/middleware/size_limit.rs
src/controller/middleware/timeout.rs
src/controller/middleware/tracing.rs
src/initializer/normalize_path.rs
src/lib.rs
src/service/http/http_service.rs
src/service/http/http_service_builder.rs
src/service/http/mod.rs
src/service/mod.rs
src/service/registry.rs
src/worker/registry.rs

Add an `AppService` trait to allow consumers to define custom services that will be run as tokio tasks. This is similar (I believe) to Laraval's `Provider` concept.
Use the `AppService` trait to add an HTTP server using Axum instead of putting http/axum specific methods directly on the `App` trait

Add `AppService` trait and use it to implement the HTTP service

---

Cargo.toml

The dependency is not used, and should be replaced by `once_cell` the functionality is needed.

Remove `lazy_static` dependency

---

examples/minimal/src/app.rs
src/controller/mod.rs
src/service/http/builder.rs
src/service/http/initializer/default.rs
src/service/http/middleware/default.rs
src/service/http/service.rs
src/service/registry.rs
src/service/worker/sidekiq/builder.rs

Update the following to thrown an error if a duplicate resource is registered:
- Worker service builder -- disallow duplicate workers or periodic jobs from being registered
- Http service builder -- disallow duplicate middleware or initializers from being registered. Note: Axum's built-in behavior is to disallow duplicate routes, so we don't need to handle that ourselves.
- Service registry -- disallow duplicate services from being registered. Note: we may want to allow this in the future -- it _may_ be useful, but will wait until we get a feature request for this before allowing it by default.

Disallow registering things multiple times

---

codecov.yml

The codecov config was invalid. Update it and validate using `https://api.codecov.io/validate`.

Fix codecov config

---

src/app.rs
src/app_context.rs
src/auth/jwt/mod.rs
src/cli/migrate.rs
src/cli/mod.rs
src/cli/print_config.rs
src/config/service/http/initializer.rs
src/config/service/http/middleware.rs
src/config/service/mod.rs
src/controller/health.rs
src/service/http/builder.rs
src/service/http/initializer/normalize_path.rs
src/service/http/middleware/catch_panic.rs
src/service/http/middleware/compression.rs
src/service/http/middleware/request_id.rs
src/service/http/middleware/sensitive_headers.rs
src/service/http/middleware/size_limit.rs
src/service/http/middleware/timeout.rs
src/service/http/middleware/tracing.rs
src/service/http/service.rs
src/service/worker/sidekiq/app_worker.rs
src/service/worker/sidekiq/builder.rs
src/service/worker/sidekiq/service.rs

This makes it slightly more ergonomic to contain the app context state with an "inner" type that's wrapped by an Arc.
This also allows consumers to disallow direct access to specific fields using clippy's
[disallowed-methods](https://rust-lang.github.io/rust-clippy/master/index.html#/disallowed_methods) lint. This is useful, for example, if consumers want to provide their own method for accessing the DB that performs some logic before/after the DB operations, e.g. for implementing RLS.

Add methods to AppContext instead of direct field access

---

examples/minimal/src/app.rs
src/app.rs
src/app_context.rs
src/service/http/service.rs
src/service/mod.rs
src/service/registry.rs
src/service/worker/sidekiq/service.rs

https://github.com/roadster-rs/roadster/issues/61

Pass config and context by reference in all public APIs

---

Cargo.toml
src/service/registry.rs

Rstest can use Tokyo as long as the annotation comes at the end.

Use Tokio for rstest tests

---

src/config/app_config.rs
src/service/http/builder.rs
src/service/http/initializer/default.rs
src/service/http/middleware/default.rs

Also, add a method to construct an empty AppConfig for testing

Add tests for the default_middleware and default_initializers methods

---

.github/workflows/coverage.yml
Cargo.toml
DEVELOPMENT.md
src/auth/jwt/ietf.rs
src/auth/jwt/mod.rs
src/auth/jwt/openid.rs
src/config/app_config.rs
src/config/service/http/initializer.rs
src/config/service/http/middleware.rs
src/lib.rs
src/service/http/builder.rs
src/service/http/initializer/default.rs
src/service/http/middleware/catch_panic.rs
src/service/http/middleware/compression.rs
src/service/http/middleware/default.rs
src/service/http/middleware/request_id.rs
src/service/http/middleware/sensitive_headers.rs
src/service/http/middleware/size_limit.rs
src/service/http/middleware/timeout.rs
src/service/http/middleware/tracing.rs
src/service/http/service.rs
src/service/mod.rs
src/service/registry.rs
src/service/worker/sidekiq/app_worker.rs
src/util/serde_util.rs

Note that ignoring coverage for tests will reduce the overall coverage percentage.

Enable coverage on nightly and add coverage(off) annotations

---

README.md

It's `unknown` now, but should be correct once we release the next version to crates.io.
Closes https://github.com/roadster-rs/roadster/issues/125

Add MSRV tag to readme

---

Cargo.toml
examples/minimal/Cargo.toml

The otel dependencies that have available updates have breaking changes that I haven't figured out how to resolve yet -- they don't seem to be documented well.

Update dependencies that can be updated

---

Cargo.toml
src/app.rs
src/cli/mod.rs
src/cli/print_config.rs
src/config/app_config.rs
src/config/service/http/initializer.rs
src/config/service/http/middleware.rs
src/config/service/http/mod.rs
src/config/service/mod.rs
src/config/service/worker/sidekiq/mod.rs
src/controller/http/docs.rs
src/service/worker/sidekiq/app_worker.rs

Most things don't need validation, so they just have the Validate derive and `#[validate(nested)]` applied to get the validations initially chained through the app config. However, we did implement a validation for the `DefaultRoutes` config.

Add validation of the AppConfig

---

src/app.rs
src/cli/mod.rs
src/controller/http/docs.rs
src/controller/http/health.rs
src/controller/http/ping.rs
src/service/http/builder.rs
src/service/mod.rs
src/service/registry.rs
src/service/worker/sidekiq/builder.rs
src/service/worker/sidekiq/service.rs

There were a couple places we were using `mock!` instead of `automock`. IIRC this was because `automock` wasn't working for `async_trait` traits; however, after reading the `mockall` docs, I found that `automock` needs to be placed _before_ `async_trait` in order for it to work. Also, specifically for the `App` trait, I just learned how to specify associated types with `automock`.
With this new knowledge, we can replace a couple manual `mock!` impls with `automock`.

Use automock to mock traits instead of the mock! macro

---

Cargo.toml

We don’t currently need a direct dependency on `time`, but the version being pulled in currently is failing to build on nightly.

Add latest version of `time` to workaround build issue on nightly

---

.github/workflows/coverage.yml

This reverts commit 6ab77d03135417a13da16ced6ca91d49de4c7a8f.

Revert "Use stable rust for coverage"

---

.github/workflows/ci.yml

There are a bunch of errors for transitive dependencies, so will not include that in our checks for now

Add `cargo-minimal-versions` for direct dependencies

---

.config/nextest.toml
Cargo.toml
examples/full/Cargo.toml
examples/full/src/app.rs
examples/full/src/lib.rs
examples/full/src/service/example.rs
examples/full/src/service/mod.rs
src/service/function/mod.rs
src/service/function/service.rs
src/service/grpc/service.rs
src/service/http/builder.rs
src/service/http/service.rs
src/service/mod.rs
src/service/registry.rs
src/service/worker/sidekiq/builder.rs
src/service/worker/sidekiq/service.rs

Closes https://github.com/roadster-rs/roadster/issues/189

Add a generic app service to run an async function as a service

---

examples/full/Cargo.toml

Without this, JetBrains IDEs on linux (at least) don't seem to be able to resolve the protobuf-generated rust files.

Enable grpc by default in the `full` example

---

src/api/cli/roadster/health.rs
src/api/cli/roadster/mod.rs
src/api/core/health.rs
src/api/core/mod.rs
src/api/http/health.rs
src/api/mod.rs

Move the underlying implementation of the `_health` HTTP API to the `core` module and update the HTTP method to call the core impl. Also, add support for invoking the health check API from the CLI using the same underlying core impl.
Closes https://github.com/roadster-rs/roadster/issues/170

Implement the health check API as a protocol agnostic `core` module

---

.github/workflows/feature_powerset.yml

Run the checks + release on Mondays as well as Fridays so that changes that are merged over the weekend don't need to wait all the way until Firday to be released.

ci: Run Feature Powerset checks + perform a release twice a week

---

src/config/app_config.rs
src/config/environment.rs

We use `.` as the env var separator in order to differentiate between the prefix and different levels of the config vs individual config field names (which would be in UPPER_SNAKE_CASE). However, `.` is not a valid bash identifier, so we need to use something different.
Switch to using a double underscore (`__`) instead of `.`. This way, we can support bash and still be able to differentiate between the prefix and different levels of the config vs individual config field names.
Note: we will continue to allow using `.` until the next breaking semver release (0.4)
Closes: https://github.com/roadster-rs/roadster/issues/219

fix: Invalid env var separator on bash

---

src/api/core/health.rs
src/app/mod.rs
src/service/mod.rs
src/service/runner.rs
src/service/worker/sidekiq/builder.rs
src/service/worker/sidekiq/service.rs

In order to allow handling CLI commands with services without requiring the sidkiq redis connection to be available, we need to move the "stale cleanup" behavior out of the "build" method so that the service can be built without needing to access redis.
This is accomplished by adding a new `AppService::before_run` trait method, which is run after all the services are built and before any of the services are run. The sidekiq service's "stale cleanup" behavior is now implemented in this trait method.
This PR also updates the health check API to run the db and redis checks in parallel.
Closes https://github.com/roadster-rs/roadster/issues/238

feat: Move sidekiq "stale cleanup" to new `before_run` service method

---

src/app/mod.rs
src/config/database/mod.rs
src/config/database/snapshots/roadster__config__database__deserialize_tests__db_config_to_connect_options.snap

Add `From<Database>` impl for `ConnectOptions` to encapsulate the conversion, which would make it easier if a consumer wants to override the default `App#db_connection_options` method but keep some of our defaults.

feat: Add `From` impl to convert db config to ConnectOptions

---

src/api/core/health.rs
src/app/mod.rs
src/config/app_config.rs
src/config/default.toml
src/config/health_check/default.toml
src/config/health_check/mod.rs
src/config/mod.rs
src/config/snapshots/roadster__config__app_config__tests__test.snap
src/health_check/database.rs
src/health_check/default.rs
src/health_check/mod.rs
src/health_check/sidekiq.rs
src/health_check/snapshots/roadster__health_check__default__tests__default_middleware@case_1.snap
src/health_check/snapshots/roadster__health_check__default__tests__default_middleware@case_2.snap
src/lib.rs
src/service/http/builder.rs
src/service/mod.rs
src/service/registry.rs
src/service/runner.rs

This is a separate trait, vs adding a "health check" method to `AppService`, to allow defining health checks that apply to multiple services. For example, most services would require the DB and Redis connections to be valid, so we would want to perform a check for these resources a single time before starting any service instead of once for every service that needs the resources.
Another benefit of using a separate trait is, because the health checks are decoupled from services, they can potentially be used in other parts of the app. For example, they could be used to implement a "health check" API endpoint.
For now, I think it makes sense to register health checks on the `ServiceRegistry` since the checks are run right before running the services, and the checks need to succeed in order …

feat: Add health checks to run before starting services

---

src/config/health_check/mod.rs
src/config/service/http/initializer.rs
src/config/service/http/middleware.rs

Similar to the middleware and initializer configs, we want to allow the consumer to access custom config options for their custom health checks.
This PR adds the `custom` field to the health check config.
Closes https://github.com/roadster-rs/roadster/issues/245

fix: Health check config is missing a `custom` field

---

src/api/http/health.rs
src/config/app_config.rs
src/config/environment.rs

In preparation for the next semver breaking release, this PR removes some things:
- An export alias for health check structs that were moved
- Removes support for using `.` as the separate for in env var names

chore!: Remove deprecated items in preparation of 0.4 release

---

src/api/core/health.rs
src/app/context.rs
src/app/mod.rs
src/health_check/default.rs
src/health_check/registry.rs
src/health_check/snapshots/roadster__health_check__default__tests__default_middleware@case_1.snap

Switch to using `OnceLock` to allow setting the health checks on the `AppContext` after it is created. The method to set the health checks is private to the crate, so we have control over when the checks are set on the context.
This has some impacts on public-facing APIs:
- `App::health_checks` takes a `&mut HealthCheckRegistry` instead of a non-mutable ref
- `AppContext::health_checks` returns the list of health checks. (Alternatively, we could have returned an Option)
- We also made the `HealthCheckRegistry::new` method non-public. This aligns with the `ServiceRegistry::new` visibility.
Closes https://github.com/roadster-rs/roadster/issues/257

feat!: Remove interior mutability of `HealthCheckRegistry`

---

src/api/core/health.rs
src/service/runner.rs

Also, log all health check failures when running health checks during app boot up.

feat: Place health check results under `resources` in response

---

examples/leptos-ssr/Cargo.toml

Profiles are ignored for packages that aren't the workspace root. Remove the profile from the example to avoid the warning that's printed.

chore: Remove unused profile from leptos-ssr example Cargo.toml

---

src/api/http/health.rs
src/health_check/mod.rs

Also, don't flatten the `custom` field of the check result.

docs: Update the `_health` HTTP API docs

---

src/api/http/docs.rs
src/service/http/builder.rs

- Add version
- Remove openapi docs from `_docs/*` routes

docs: Fixes for default openapi docs

---

src/service/http/builder.rs

The `HttpServiceBuilder#api_router` method is incorrectly adding the provided `ApiRouter` to the normal axum `Router`. This means the routes defined in the provided `ApiRouter` will not show up in the generated OpenAPI schema.
Fix the method to correctly merge the provided `ApiRouter` with the `HttpServiceBuilder`'s `ApiRouter`.

fix: Correctly add the `ApiRouter` to the HTTP service's `ApiRouter`

---

justfile

This command updates dependencies in our Cargo.toml, which we really only want to do sparingly -- we don't want to unnecessarily bump a minor/patch version of a dep, for example.

chore: Remove the `update` justfile command

---

src/migration/schema.rs
src/migration/snapshots/roadster__migration__schema__tests__pk_bigint@pk_bigint.snap
src/migration/snapshots/roadster__migration__schema__tests__pk_bigint_identity@pk_bigint_identity.snap
src/migration/snapshots/roadster__migration__schema__tests__pk_bigint_identity_options@case_1.snap
src/migration/snapshots/roadster__migration__schema__tests__pk_bigint_identity_options@case_2.snap
src/migration/snapshots/roadster__migration__schema__tests__pk_bigint_identity_options@case_3.snap
src/migration/snapshots/roadster__migration__schema__tests__pk_bigint_identity_options@case_4.snap
src/migration/user/create_and_drop_table.rs
src/migration/user/snapshots/roadster__migration__user__create_and_drop_table__tests__create_table_int_pk.snap

`BIGSERIAL` is not recommended. See: https://wiki.postgresql.org/wiki/Don%27t_Do_This#Don.27t_use_serial. The recommendation is instead to use `IDENTITY` columns.
This PR updates the create `user` table migration (just the one using bigint as the primary key) to create the pk as an IDENTITY column instead of a BIGSERIAL. This PR also adds the `pk_bigint_identity` method to enable creating an IDENTITY pk in any table. The `pk_bigint_identity_options` method is added as well, which is the same except it allows configuring the sequence for the identity generation. See: https://www.postgresql.org/docs/current/sql-createsequence.html
Closes https://github.com/roadster-rs/roadster/issues/290

feat: Use IDENTITY column for int primary keys instead of BIGSERIAL

---

src/migration/schema.rs
src/migration/snapshots/roadster__migration__schema__tests__pk_uuid_default@pk_uuid_default.snap
src/migration/snapshots/roadster__migration__schema__tests__pk_uuid_v4@pk_uuid_v4.snap
src/migration/snapshots/roadster__migration__schema__tests__pk_uuid_v7@pk_uuid_v7.snap
src/migration/snapshots/roadster__migration__schema__tests__uuid_default@uuid_default.snap
src/migration/snapshots/roadster__migration__schema__tests__uuid_v4@uuid_v4.snap
src/migration/snapshots/roadster__migration__schema__tests__uuid_v7@uuid_v7.snap
src/migration/user/snapshots/roadster__migration__user__create_and_drop_table__tests__create_table_uuid_pk.snap

Closes https://github.com/roadster-rs/roadster/issues/295

feat: Add non-pk versions of uuid schema helper methods

---

Cargo.toml
justfile
src/config/service/http/default.toml
src/config/service/http/middleware.rs
src/config/snapshots/roadster__config__app_config__tests__test.snap
src/service/http/middleware/default.rs
src/service/http/middleware/tracing/mod.rs
src/service/http/middleware/tracing/req_res_logging.rs

It can be useful when developing an application to be able to see the request/response bodies as they are seen by the server. Add an Axum middleware to do this. Because the middleware buffers the entire request/response, it is disabled by default. If we add a mechanism to provide different defaults per environment, this middleware may be enabled in non-prod environments by default in the future.

feat: Add middleware to log the request/response payloads

---

src/config/app_config.rs
src/config/service/http/config/default.toml
src/config/service/http/config/production.toml
src/config/service/http/mod.rs
src/config/snapshots/roadster__config__app_config__tests__test.snap
src/service/http/middleware/snapshots/roadster__service__http__middleware__default__tests__default_middleware@case_2.snap
src/service/http/middleware/tracing/req_res_logging.rs

Update the default app config to allow different defaults per environment, so ReqResLogging middleware can be enabled by default, but disabled in prod.

feat: Enable ReqResLogging middleware by default, but disable in prod

---

src/config/service/http/config/default.toml
src/config/service/http/config/production.toml
src/config/service/http/middleware.rs
src/config/snapshots/roadster__config__app_config__tests__test.snap
src/service/http/middleware/default.rs
src/service/http/middleware/tracing/req_res_logging.rs

Some payloads can be massive, so it's a good idea to add a limit to the size of log that will be emitted by the
`RequestResponseLoggingMiddleware`. To remove the limit, the `max-len` config can be set to a negative number.
Closes https://github.com/roadster-rs/roadster/issues/306

feat: Allow configuring the max len for the `ReqResLoggingMiddleware`

---

Cargo.toml
src/config/auth/mod.rs
src/error/auth.rs
src/error/axum.rs
src/middleware/http/auth/jwt/ietf.rs
src/middleware/http/auth/jwt/mod.rs
src/middleware/http/auth/jwt/openid.rs

If the `BearerAuthHeader` header is missing, attempt to get the JWT from the `AUTHORIZATION` header. If the JWT is not available from either source, reject the response with an "unauthorized" response.

feat: Extract JWT from cookie

---

examples/leptos-ssr/src/server/mod.rs

Using `leptos_routes_with_context` to provide the state as a context is redundant and can cause errors.

fix: Use `leptos_routes` in leptos example instead of `leptos_routes_with_context`

---

src/middleware/http/auth/jwt/mod.rs
src/middleware/http/auth/jwt/snapshots/roadster__middleware__http__auth__jwt__tests__subject_from_string@case_1.snap
src/middleware/http/auth/jwt/snapshots/roadster__middleware__http__auth__jwt__tests__subject_from_string@case_2.snap
src/middleware/http/auth/jwt/snapshots/roadster__middleware__http__auth__jwt__tests__subject_from_string@case_3.snap
src/middleware/http/auth/jwt/snapshots/roadster__middleware__http__auth__jwt__tests__subject_from_string@case_4.snap
src/middleware/http/auth/jwt/snapshots/roadster__middleware__http__auth__jwt__tests__subject_from_u16@subject_from_u16.snap
src/middleware/http/auth/jwt/snapshots/roadster__middleware__http__auth__jwt__tests__subject_from_u32@subject_from_u32.snap
src/middleware/http/auth/jwt/snapshots/roadster__middleware__http__auth__jwt__tests__subject_from_u64@subject_from_u64.snap
src/middleware/http/auth/jwt/snapshots/roadster__middleware__http__auth__jwt__tests__subject_from_u8@subject_from_u8.snap
src/middleware/http/auth/jwt/snapshots/roadster__middleware__http__auth__jwt__tests__subject_from_uri.snap
src/middleware/http/auth/jwt/snapshots/roadster__middleware__http__auth__jwt__tests__subject_from_uuid@subject_from_uuid.snap
src/testing/snapshot.rs
src/testing/snapshots/roadster__testing__snapshot__tests__bearer_token@case_1.snap
src/testing/snapshots/roadster__testing__snapshot__tests__bearer_token@case_2.snap
src/testing/snapshots/roadster__testing__snapshot__tests__bearer_token@case_3.snap
src/testing/snapshots/roadster__testing__snapshot__tests__bearer_token@case_4.snap
src/testing/snapshots/roadster__testing__snapshot__tests__bearer_token@case_5.snap

Also, implement `From` for various `Subject` enum variants.

feat: Redact bearer tokens in insta snapshots

---

src/config/auth/mod.rs
src/middleware/http/auth/jwt/mod.rs
src/middleware/http/auth/jwt/snapshots/roadster__middleware__http__auth__jwt__tests__bearer_token_from_cookies@invalid_token.snap
src/middleware/http/auth/jwt/snapshots/roadster__middleware__http__auth__jwt__tests__bearer_token_from_cookies@valid_token.snap

This approach is/may be  vulnerable to a CSRF attack. More care/research is needed before taking this approach. For now, it's safer to simply use the authorization header.

fix: Do not simply use bearer token from cookie for auth

---

src/config/auth/mod.rs
src/config/auth/snapshots/roadster__config__auth__tests__auth@case_2.snap
src/config/auth/snapshots/roadster__config__auth__tests__auth@case_3.snap
src/config/auth/snapshots/roadster__config__auth__tests__auth@case_4.snap
src/config/auth/snapshots/roadster__config__auth__tests__auth@case_5.snap
src/config/snapshots/roadster__config__app_config__tests__test.snap
src/middleware/http/auth/jwt/mod.rs
src/middleware/http/auth/jwt/snapshots/roadster__middleware__http__auth__jwt__tests__bearer_token_from_cookies@invalid_token.snap
src/middleware/http/auth/jwt/snapshots/roadster__middleware__http__auth__jwt__tests__bearer_token_from_cookies@valid_token.snap

Getting the JWT from the cookie seems to be acceptable, and is useful for GET requests (e.g., initial page load when using SSR). However, for POST requests it should be accompanied with some CSRF protection mechanism. At the moment, the CSRF validation will need to be performed by the consuming application.

feat: Allow jwt from cookie, but only if it's explicitly requested

---

examples/leptos-ssr/Cargo.toml
src/middleware/http/auth/jwt/mod.rs

Add a new axum extractor called `JwtCsrf` that allows extracting the JWT from a cookie (if the `auth.jwt.cookie-name` config is set). This extractor provides some metadata about whether it's safe to use the JWT or if a CSRF protection mechanism needs to be applied first.
With this, we also remove cookie extraction from the normal `Jwt`, so it can safely be used without any CSRF protection mechanisms.

feat: Remove cookie extraction for `Jwt`, but allow it in `JwtCsrf`

---

examples/full/src/app.rs
examples/leptos-ssr/src/server/mod.rs
src/app/context.rs
src/app/mod.rs
src/service/function/service.rs
src/service/runner.rs

It may be useful for consumers to be able to put state on their App implementation that they can use in the app trait. For example, I wanted this when I was working on generating an OpenAPI client from the app's Aide OpenAPI schema.
Also, this would be needed in order to support a builder-style approach to building the app. This would allow us to provide a default app impl configured with a builder-style api. We may still allow consumers to directly use the trait impl if they want.
Closes https://github.com/roadster-rs/roadster/issues/272

feat!: App methods take `self`

---

config/default.toml
examples/full/config/default.toml
examples/leptos-ssr/Cargo.toml
examples/leptos-ssr/src/server/mod.rs

Also provide commented-out example of listening on all ipv4 and ipv6 in order to allow connections from LAN for development

chore: Update leptos example to use site-addr and env from roadster config

---

examples/full/config/default.toml
examples/full/config/default/database.toml
examples/full/config/default/sidekiq.toml
examples/full/config/development.toml
examples/full/config/development/sidekiq.toml
src/config/app_config.rs

As an application grows, it will need to define many different config fields. This can easily become unweildy to maintain in a single file.
This PR adds support for env-specific config directories. All config files (`.toml` only currently) in the env's directory will be merged into the final config at runtime. The directory is traversed recursively, so nested directory structures are supported.

feat: Allow splitting config files into many files in env directories

---

src/migration/schema.rs
src/migration/timestamp/m20240723_201404_add_update_timestamp_function.rs
src/migration/timestamp/mod.rs
src/migration/user/m20240724_005115_user_update_timestamp.rs
src/migration/user/mod.rs

Making this public will enable consumers to create foreign-key constraints on fields created by the `UserMigrator`.

feat: Make the `User` sea-orm migration enum public

---

src/config/service/http/config/default.toml
src/config/snapshots/roadster__config__app_config__tests__test.snap

These aren't standard headers, but we can provide them as a default in case they exist and we decide to make them a convention in Roadster in the future.

feat: Mark refresh token headers as sensitive

---

Cargo.toml
src/app/mod.rs
src/config/database/mod.rs
src/config/database/snapshots/roadster__config__database__deserialize_tests__db_config_to_connect_options.snap
src/config/database/snapshots/roadster__config__database__deserialize_tests__sidekiq@case_1.snap
src/config/database/snapshots/roadster__config__database__deserialize_tests__sidekiq@case_2.snap
src/config/snapshots/roadster__config__app_config__tests__test.snap

Sea-orm added support for lazy database connections. We provide a config field to allow toggling lazy database connections on or off. If lazy connections are enabled, the default `run` method will allow running CLI commands without requiring the the DB connection to be available (unless the CLI command itself attempts to execute a DB query).
Closes https://github.com/roadster-rs/roadster/issues/235

feat: Allow running CLI commands without requiring DB/Redis connections

---

src/app/mod.rs
src/config/app_config.rs
src/config/default.toml
src/config/health_check/mod.rs
src/config/lifecycle/default.toml
src/config/lifecycle/mod.rs
src/config/mod.rs
src/config/snapshots/roadster__config__app_config__tests__test.snap
src/health_check/default.rs
src/health_check/mod.rs
src/lib.rs
src/lifecycle/db_migration.rs
src/lifecycle/default.rs
src/lifecycle/mod.rs
src/lifecycle/registry.rs
src/service/http/initializer/default.rs
src/service/http/middleware/default.rs
src/service/runner.rs

Add `AppLifecycleHandler` trait with methods that are called at various stages of an app's lifecycle. The initial set of methods are the following:
- `before_service_cli`
- `before_health_checks`
- `before_services`
- `on_shutdown`
Closes https://github.com/roadster-rs/roadster/issues/350

feat: Add lifecycle handlers

---

src/api/cli/roadster/mod.rs
src/app/mod.rs
src/config/app_config.rs

Closes https://github.com/roadster-rs/roadster/issues/356

feat: Allow specifying a custom config dir

---

examples/app-builder/src/health_check/example.rs
examples/app-builder/src/lifecycle/example.rs
examples/app-builder/src/main.rs
src/app/mod.rs
src/app/roadster_app.rs
src/health_check/registry.rs
src/lifecycle/registry.rs
src/service/registry.rs

Allow providing most fields of the `RoadsterApp` directly instead of in provider callback methods. This can be useful if the consumer doesn't need the app context/state to build an item and they don't want to deal with creating a callback lambda/method.
The `app-builder` example was updated to use all the new methods.

feat: Add more builder methods for `RoadsterApp`

---

Cargo.toml

This reverts commit c6c699f5f16a9581cd5904f3ae6d14df0bd8876f.

chore: Revert "chore: Update Otel and tower-http dependencies (#374)"

---

.github/workflows/ci.yml
.github/workflows/coverage.yml
.github/workflows/feature_powerset.yml

I'm not sure if this really helps much -- the CI time is largely dominated by compilation time vs linker time I believe. It doesn't seem to hurt though.
Closes https://github.com/roadster-rs/roadster/issues/378

ci: Use mold linker in CI

---

Cargo.toml

For some reason, I'm getting an issue locally where the `rstest_macros` crate can't be found:
```
error[E0463]: can't find crate for rstest_macros
--> /home/spencer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rstest-0.22.0/src/lib.rs:570:9
|
570 | pub use rstest_macros::fixture;
|         ^^^^^^^^^^^^^ can't find crate
```
This doesn't occur in CI so I think something is wrong with my dev env. However, removing the default features from `rstest` seems to resolve this locally, and we don't need the default features in `roadster`.

chore: Disable default features for `rstest`

---

Cargo.toml
examples/app-builder/Cargo.toml
examples/full/Cargo.toml
examples/leptos-ssr/Cargo.toml
src/app/context.rs
src/config/email/smtp.rs
src/error/email.rs
src/error/mod.rs

Use the smtp connection details from the `AppConfig::email::smtp` config to build an smtp client using the `lettre` crate.

feat: Add smtp client to `AppContext`

---

.cargo-husky/hooks/pre-push
README.md
examples/full/README.md
examples/full/config/development/email.toml
src/config/email/smtp.rs
src/config/email/snapshots/roadster__config__email__smtp__tests__serialization@case_6.snap

Also, update READMEs to add instructions for how to start a local smtp server for dev/testing.
Also, don't run pre-push checks against entire workspace, just roadster

feat: Allow specifying the smtp port via config

---

Cargo.toml
examples/leptos-ssr/Cargo.toml
justfile
src/error/axum.rs
src/error/mime.rs
src/error/mod.rs
src/service/http/middleware/tracing/req_res_logging.rs

Some req/res body content types are more useful to log than others. For example, it's not generally helpful to log `image/x-icon` or `text/javascript`. However, it can still be very useful for debugging to log things like `application/json` or
`application/x-www-form-urlencoded`.
Allow configuring which content types to allow to be logged. By default, all content types are allowed. Currently, only exact matches of content types are supported, so using `text/*` will not match `text/plain`, for example.
Closes https://github.com/roadster-rs/roadster/issues/390

feat: Allow configuring which req/res body content types to log

---

.github/workflows/book.yml
.github/workflows/ci.yml
Cargo.toml
book/book.toml
book/examples/chapter_1/Cargo.toml
book/examples/chapter_1/src/main.rs
book/src/chapter_1.md
justfile

- Enable including rust snippets from other files in mdbook
- Run tests against book examples in ci
- Run `mdbook test` in ci
- Add some justfile commands to contain testing logic -- we're manually iterating over workspace members instead of using cargo's workspace features

ci: Test mdbook before deploying

---

examples/full/config/default.toml
examples/full/config/development.toml
examples/full/src/api/http/mod.rs
examples/full/src/app.rs
src/config/mod.rs
src/config/service/http/middleware.rs
src/service/http/middleware/any.rs
src/service/http/middleware/mod.rs

If a consumer wants to use a middleware that's not already supported by Roadster, they need to implement the `Middleware` trait, which is extra boilerplate that could be annoying.
Add `AnyMiddleware` struct that implements the `Middleware` trait, so consumers just need to provide the name of the middleware and the logic to build/configure it.
Closes https://github.com/roadster-rs/roadster/issues/470

feat: Add `AnyMiddleware` to minimize boilerplate for Axum middleware

---

examples/full/src/api/http/mod.rs
examples/full/src/app.rs
src/service/http/builder.rs
src/service/http/initializer/any.rs
src/service/http/initializer/mod.rs
src/service/http/middleware/any.rs

If a consumer wants to initialize the Axum Router in a way that's not already supported by Roadster, they need to implement the `Initializer` trait, which is extra boilerplate that could be annoying.
Add `AnyInitializer` struct that implements the `Initializer` trait, so consumers just need to provide the name of the initializer and the logic to build/configure the Axum Router.
Note: This PR also contains a breaking change to `AnyMiddleware`. However, since this was just released a few hours ago, I doubt anyone is using it yet, so it should be relatively safe to just release the breaking change in a patch update.
Closes https://github.com/roadster-rs/roadster/issues/473

feat: Add `AnyInitializer` to minimize boilerplate for initializers

---

src/migration/collation/m20241022_065427_case_insensitive_collation.rs
src/migration/collation/mod.rs
src/migration/collation/snapshots/roadster__migration__collation__tests__create_case_insensitive_collation_for_db_backend@case_1.snap
src/migration/collation/snapshots/roadster__migration__collation__tests__create_case_insensitive_collation_for_db_backend@case_2.snap
src/migration/collation/snapshots/roadster__migration__collation__tests__create_case_insensitive_collation_for_db_backend@case_3.snap
src/migration/collation/snapshots/roadster__migration__collation__tests__drop_case_insensitive_collation_for_db_backend@case_1.snap
src/migration/collation/snapshots/roadster__migration__collation__tests__drop_case_insensitive_collation_for_db_backend@case_2.snap
src/migration/collation/snapshots/roadster__migration__collation__tests__drop_case_insensitive_collation_for_db_backend@case_3.snap
src/migration/mod.rs
src/migration/timestamp/m20240723_201404_add_update_timestamp_function.rs
src/migration/timestamp/mod.rs
src/migration/user/m20241022_072216_case_insensitive_username_email.rs
src/migration/user/mod.rs
src/migration/user/snapshots/roadster__migration__user__m20241022_072216_case_insensitive_username_email__tests__down_statements@case_1.snap
src/migration/user/snapshots/roadster__migration__user__m20241022_072216_case_insensitive_username_email__tests__down_statements@case_2.snap
src/migration/user/snapshots/roadster__migration__user__m20241022_072216_case_insensitive_username_email__tests__down_statements@case_3.snap
src/migration/user/snapshots/roadster__migration__user__m20241022_072216_case_insensitive_username_email__tests__up_statements@case_1.snap
src/migration/user/snapshots/roadster__migration__user__m20241022_072216_case_insensitive_username_email__tests__up_statements@case_2.snap
src/migration/user/snapshots/roadster__migration__user__m20241022_072216_case_insensitive_username_email__tests__up_statements@case_3.snap
src/migration/user/snapshots/roadster__migration__user__tests__user_migrator_migrations.snap
src/service/worker/sidekiq/builder.rs

Problem
-------
It's common for typos to occur when entering usernames and emails that result in random incorrect capitalization. Additionally, it's both a security vulnerability and a usability issue if multiple users can have the same username/email just with different capitalization.
Solution
--------
- Add a case-insensitive collation (we only officially support this on Postgres
- Assign the Username and Email columns of the User table to use the case-insensitive collation.
Closes https://github.com/roadster-rs/roadster/issues/479

feat: Case-insensitive username and email fields

---

Cargo.toml
deny.toml

Closes https://github.com/roadster-rs/roadster/issues/447

chore: Remove resolved advisory from deny ignore list

---

src/config/mod.rs
src/config/service/common/address.rs
src/config/service/common/snapshots/roadster__config__service__common__address__tests__url_with_scheme@case_1.snap
src/config/service/common/snapshots/roadster__config__service__common__address__tests__url_with_scheme@case_2.snap
src/config/service/grpc/config/default.toml
src/config/service/grpc/config/production.toml
src/config/service/grpc/mod.rs
src/config/service/http/config/default.toml
src/config/service/http/config/production.toml
src/config/service/http/mod.rs
src/config/snapshots/roadster__config__tests__test.snap
src/error/mod.rs
src/error/parse.rs

Also, add some parse errors to the Roadster Error enum.

feat: Add config to specify the domain where the service is hosted

---

Cargo.toml
src/api/core/health.rs
src/app/context.rs
src/app/mod.rs
src/config/database/mod.rs
src/config/mod.rs
src/config/service/worker/sidekiq/mod.rs
src/service/runner.rs

Add support for TestContainers to make it easy to set up independent test environments to allow running tests in parallel without risk of cross-contamination even if they touch the DB.
TestContainers support is behind the `test-containers` flag. When the flag is enabled, the consumer can enable TestContainers for the DB and Sidekiq Redis in the `AppConfig`, in which case a TestContainer instance will be create when building the `AppContext`, and the URI in the `AppConfig` will be updated to match that of the TestContainer instance.
Additionally, a new method was added to `AppConfig` to allow consumers to create it themselves. This would allow consumers more control over the config, including manually creating a TestContainer instance and updating the URI of a field in the `AppConfig` …

feat: Add support for TestContainers (pgsql + redis modules)

---

Cargo.toml
examples/full/src/app_state.rs
src/app/context.rs

Also, annotate with `mockall::automock` when the new `testing-mocks` feature is enabled to allow consumers to easily provide mocks to methods expecting a trait impl.
This is significantly simpler than mocking the `AppContext` struct itself, so we will not do that for now. We can consider doing it later if people really want it.
Closes https://github.com/roadster-rs/roadster/issues/495

feat: `Provide` and `ProvideRef` traits to provide `AppContext` objects

---

Cargo.toml
examples/app-builder/src/model/mod.rs
examples/full/Cargo.toml
examples/full/src/model/mod.rs
examples/full/src/model/user.rs
src/app/context.rs
src/service/runner.rs

Add an example of using `MockProvideRef<DatabaseConnection>` to provide a `MockDatabase` from SeaORM in a test.

docs: Use `MockProvideRef<DatabaseConnection>` in an example test

---

src/error/sidekiq.rs

Add `From` impl to allow converting a `roadster::Error` into a `sidekiq::Error`. This makes writing worker code more ergonomic.
Closes https://github.com/roadster-rs/roadster/issues/488

feat: Enable converting `roadster::Error` to `sidekiq::Error`

---

Cargo.toml
src/app/context.rs
src/health_check/database.rs
src/health_check/default.rs
src/health_check/email/smtp.rs
src/health_check/mod.rs
src/health_check/sidekiq_enqueue.rs
src/health_check/sidekiq_fetch.rs

This is useful for preventing reference cycles between things that are held in the `AppContext` and also need a reference to the `AppContext`; for example, `HealthCheck`s.
Closes https://github.com/roadster-rs/roadster/issues/526

feat: Add `AppContextWeak` to prevent reference cycles

---

src/lib.rs
src/service/worker/sidekiq/app_worker.rs

Allow enqueuing delayed sidekiq jobs via the `AppWorker` trait.

feat: Add `AppWorker#enqueue_delayed`

---

Cargo.toml
src/config/service/http/config/default.toml
src/config/service/http/middleware.rs
src/config/snapshots/roadster__config__tests__test.snap
src/service/http/middleware/cache_control.rs
src/service/http/middleware/default.rs
src/service/http/middleware/etag.rs
src/service/http/middleware/mod.rs
src/service/http/middleware/snapshots/roadster__service__http__middleware__default__tests__default_middleware@case_2.snap

Add two middlewares related to browser caching:
- CacheControlMiddleware: Sets the `cache-control` header for configured content types
- EtagMiddleware: Handles an `etag` header in request/response headers. If the header value is the same in the req and res, then a 304 is returned with an empty body.
Closes https://github.com/roadster-rs/roadster/issues/538

feat: Add cache-related middlewares

---

src/config/database/mod.rs
src/config/health_check/mod.rs
src/config/lifecycle/mod.rs
src/config/mod.rs
src/config/service/http/default_routes.rs
src/config/service/http/initializer.rs
src/config/service/http/middleware.rs
src/config/service/mod.rs
src/service/http/initializer/normalize_path.rs
src/service/http/middleware/cache_control.rs
src/service/http/middleware/request_id.rs
src/service/http/middleware/sensitive_headers.rs

Custom configs will need to be validated separately by the consumer after they deserialize the embedded `Value` into a specific type.
Closes https://github.com/roadster-rs/roadster/issues/358

fix: Propagate `Validate` calls to all app config fields

---

Cargo.toml

`0.15.5` had a regression that was fixed in `0.15.6` (in [this PR](https://github.com/rust-cli/config-rs/pull/627)), so we need at least that version
Closes https://github.com/roadster-rs/roadster/issues/534

chore: Update `config` to 0.15.6

---

Cargo.toml
src/api/core/health.rs
src/app/context.rs
src/service/worker/sidekiq/builder.rs

To help prevent using the wrong redis pool to enqueue vs fetch, return the connection pools wrapped in "new-type" structs.

feat!: Return `RedisEnqueue` and `RedisFetch` redis pool "new-types"

---

examples/full/config/default.toml
examples/full/src/app.rs
examples/full/src/app_state.rs
examples/full/src/health/example.rs
examples/full/src/health/mod.rs
examples/full/src/lib.rs
src/app/mod.rs
src/health_check/mod.rs

Uses a weak pointer version of the `AppState` to demonstrate how to use the weak pointer to break the reference cycle between heath checks and the `AppContext`.
Closes https://github.com/roadster-rs/roadster/issues/574

docs: Add `ExampleHealthCheck` to the `full` example

---

src/app/mod.rs
src/config/lifecycle/default.toml
src/config/lifecycle/mod.rs
src/config/snapshots/roadster__config__tests__test.snap
src/lifecycle/db/graceful_shutdown.rs
src/lifecycle/db/migration.rs
src/lifecycle/db/mod.rs
src/lifecycle/default.rs
src/lifecycle/mod.rs
src/service/runner.rs

Removed in favor of the `AppLifecycleHandler` hooks.

chore!: Remove the `App#graceful_shutdown` method

---

examples/app-builder/src/lib.rs
examples/app-builder/src/main.rs
src/app/mod.rs
src/app/roadster_app.rs
src/util/empty.rs
src/util/mod.rs

Use conditional compilation of type parameters of `RoadsterApp` to enable/disable the bounds on the type parameters depending on which features are enabled. This allows us to have a single implementation of `RoadsterApp` instead of having multiple implementations that are conditionally compiled using `cfg_if`, greatly reducing code duplication and our maintenance burden.
A downside of this approach is RustRover seems to not play super well with the conditionally compiled type parameters. It seems to sometimes ignore the conditional compilation, leading to it thinking that there are 5 type parameters even though two sets of them are mutually exclusive and can't be enabled at the same time so there should only ever be 3 type parameters. However, things compile and we can write our code in a …

chore: Refactor `RoadsterApp` to reduce duplication

---

Cargo.toml
README.md
book/src/features/database/index.md
examples/app-builder/Cargo.toml
examples/app-builder/migration/Cargo.toml
examples/app-builder/src/lib.rs
examples/app-builder/src/main.rs
examples/full/migration/Cargo.toml
private/powerset_matrix/src/main.rs
src/api/cli/mod.rs
src/api/cli/roadster/mod.rs
src/api/cli/roadster/print_config.rs
src/api/core/health.rs
src/app/context.rs
src/app/mod.rs
src/app/roadster_app.rs
src/config/health/check/mod.rs
src/config/lifecycle/mod.rs
src/config/mod.rs
src/error/mod.rs
src/health/check/default.rs
src/health/check/mod.rs
src/lib.rs
src/lifecycle/default.rs
src/lifecycle/mod.rs
src/util/empty.rs

We'd like to add support for Diesel, so we should have a separate feature flag for sea-orm vs diesel. Add a `db-sea-orm` flag and replace all instances of `db-sql` with it. We'll keep the old `db-sql` feature as well for now in case there's any common code to use between both, for example, app config fields.

feat!: Add `db-sea-orm` feature to prepare for other DB crate support

---

src/config/mod.rs

Use kebab case for the environment env var config override instead of lowercase. This way, if we ever change the env var name, it will be correctly mapped to kebab case which is what we use for the rest of the config fields.

fix: Kebab case for environment env var instead of lowercase

---

Cargo.toml

Currently `lettre` and `reqwest` use `native-tls` whilst several other dependencies have explicitly specified `rustls`. The nested system dependancy on `libssl` makes building and deploying on alpine very annoying (theoretically possible, but as yet no luck in my current project).
Given the mismatch and difficulties with `openssl`, it makes sense to me to consolidate on `rustls`

chore: Replace native-tls with rustls in several dependencies

---

book/examples/app-config/src/lib.rs
book/examples/app-context/src/app.rs
book/examples/database/src/roadster_app.rs
book/examples/service/src/http/open_api.rs
book/examples/service/src/lib.rs
examples/app-builder/src/lib.rs
src/lifecycle/registry.rs
src/service/function/service.rs
src/service/registry.rs

`Empty` is the default `Cli` type for the `RoadsterApp` if none is provided, so we don't need to specify it.
This partially addresses https://github.com/roadster-rs/roadster/issues/616, but I don't want to close that yet in case I can think of how to remove the associated type entirely.

docs: Remove unnecessary `Empty` for `RoadsterApp` `Cli` type

---

book/src/SUMMARY.md
book/src/changelog.md
book/src/comparisons/loco.md
examples/app-builder/config/test.toml
src/api/cli/mod.rs
src/api/cli/roadster/migrate.rs
src/app/mod.rs
src/app/snapshots/roadster__app__tests__prepare_options_test.snap

The `run_test*` functions were parsing the CLI, which results in the tests failing due to unexpected parameters.
Refactor some methods in `roadster::app` to allow skipping the CLI even if the feature flag is enabled. This (for now) requires making the cli fields optional in the prepared app. Maybe we can figure out a better solution in the future.

fix!: Fix `run_test*` to skip CLI

---

src/app/prepare.rs
src/app/snapshots/roadster__app__prepare__tests__prepare_options_test.snap
src/config/mod.rs

Add fields to `PrepareOptions` to allow providing custom config sources and/or overriding specific config fields. Also allow overriding the entire `AppConfig` if desired.

feat: Allow overriding config fields or entire config

---

book/examples/app-config/Cargo.toml
book/examples/app-context/Cargo.toml
book/examples/auth/Cargo.toml
book/examples/ch-02-getting-started/Cargo.toml
book/examples/ch-02-getting-started/src/main.rs
book/examples/database-diesel/Cargo.toml
book/examples/database/Cargo.toml
book/examples/open-api/Cargo.toml
book/examples/open-api/src/http/mod.rs
book/examples/open-api/src/lib.rs
book/examples/service/Cargo.toml
book/examples/service/src/http/mod.rs
book/examples/service/src/http/open_api.rs
book/src/features/open-api.md

It's largely duplicated with part of the http service chapter, so maybe we don't super need it, but I'll keep it for now.

docs: Expand OpenAPI chapter

---

clippy.toml
src/api/cli/roadster/list_routes.rs
src/api/cli/roadster/migrate.rs
src/api/cli/roadster/open_api.rs
src/api/core/health.rs
src/app/context.rs
src/app/roadster_app.rs
src/config/environment.rs
src/db/migration/diesel/mod.rs
src/error/cli.rs
src/error/db.rs
src/error/mod.rs
src/error/other.rs
src/error/sidekiq.rs
src/error/snapshots/roadster__error__tests__into_response@case_10.snap
src/error/snapshots/roadster__error__tests__into_response@case_11.snap
src/health/check/registry.rs
src/health/check/sidekiq_fetch.rs
src/lifecycle/registry.rs
src/service/grpc/service.rs
src/service/http/builder.rs
src/service/http/middleware/size_limit.rs
src/service/runner.rs
src/service/worker/sidekiq/builder.rs

Closes https://github.com/roadster-rs/roadster/issues/737

feat: Remove usages of `anyhow`

---

src/app/context.rs
src/testing/snapshot.rs
src/tracing/mod.rs

Updates the test db name to be of the format
`tmp/<mod_path_initials>/<test_name>[/<case_name>]/<timestamp>`.
This will make it easier to find the DB involved in a test,
including allowing sorting by the test run timestamp.
Closes https://github.com/roadster-rs/roadster/issues/736

feat: Use the test name as the test db name

---

src/service/http/middleware/tracing/mod.rs

The OTEL semantic conventions specify that an HTTP request span should be named `{method} {target}` if the method and target (route) are available. The `tracing-opentelemtry` crate allows setting a dynamic span name using the `otel.name` field, which allows us to use the method/route in the span name.
This PR also sets the http span kind as `SERVER`

feat: Set HTTP request span name as `{method} {route}`

---

.github/workflows/book.yml
.github/workflows/ci.yml
.github/workflows/coverage.yml

The `taiki-e/install-action` github action allows installing multiple tools at once. We were previously invoking the action multiple times, once for each tool. This PR combines the separate invocations into one.

ci: Combine multiple taiki-e tasks into one

---

Cargo.lock
Cargo.toml
book/examples/email/Cargo.toml
book/examples/email/src/worker/email/sendgrid.rs
book/examples/email/src/worker/email/smtp.rs
book/examples/email/src/worker/email/smtp_leptos.rs
private/powerset_matrix/Cargo.toml
private/powerset_matrix/src/cli.rs
private/powerset_matrix/src/main.rs
src/api/cli/roadster/migrate.rs
src/app/metadata.rs
src/app/prepare.rs
src/app/snapshots/roadster__app__prepare__tests__prepare_options_test.snap
src/config/mod.rs
src/db/migration/mod.rs
src/db/migration/sea_orm/schema.rs
src/health/check/mod.rs
src/middleware/http/auth/jwt/ietf.rs
src/middleware/http/auth/jwt/mod.rs
src/middleware/http/auth/jwt/openid.rs
src/service/function/service.rs
src/service/http/initializer/any.rs
src/service/http/middleware/any.rs
src/service/http/service.rs
src/testing/snapshot.rs
src/worker/config.rs

The resulting APIs are mostly compatible. However, optional setters were renamed from `*_opt` to `maybe_*`.

chore!: Migrate from `typed-builder` to `bon`

---

src/worker/mod.rs

`Worker::enqueue` allows passing either an owned variable or a ref, but this was missed when defining `enqueue_delayed`, `enqueue_batch`, and `enqueue_batch_delayed`. This PR updates the defs to allow either owned or ref variables.

fix: Allow enqueue_delayed and enqueue_batch* to take owned or ref

---

Cargo.lock
Cargo.toml
examples/app-builder/Cargo.toml
examples/app-builder/src/lib.rs
src/service/http/middleware/tracing/mod.rs
src/util/mod.rs
src/util/tracing.rs
src/worker/backend/pg/enqueue.rs
src/worker/backend/pg/processor/mod.rs
src/worker/backend/sidekiq/enqueue.rs
src/worker/backend/sidekiq/processor/builder.rs
src/worker/backend/sidekiq/processor/mod.rs
src/worker/backend/sidekiq/roadster_worker.rs
src/worker/job.rs
src/worker/mod.rs
src/worker/snapshots/roadster__worker__job__tests__job_serde@job_serde.snap
src/worker/snapshots/roadster__worker__job__tests__job_serde_no_periodic@job_serde_no_periodic.snap

To help with tracking background jobs in a uniform way across different worker backends, add an `id` field to our internal `Job` struct. The ID is logged at the debug level when the job is enqueued, at error level when an error occurs, and is added to the trace span around the worker's `handle` method.
This is technically a breaking change because any jobs that were enqueued before this change will not deserialize properly due to the missing `id` field. Additionally, our sidekiq integration was changed to enqueue the entire `Job` struct instead of just the args.

feat!: Add `id` field to internal `Job` struct

---

.github/workflows/ci.yml
.github/workflows/feature_powerset.yml
Cargo.toml
book/examples/app-context/Cargo.toml
book/examples/database-diesel/Cargo.toml
book/examples/database/Cargo.toml
examples/diesel/Cargo.toml
examples/full/Cargo.toml
src/config/database/mod.rs
src/worker/mod.rs

Updates the `default` feature to remove sea-orm. Roadster no longer suggests a particular DB solution as the default. Instead, consumers should enable the `db-sea-orm` or `db-diesel-*` feature depending on the preferred solution.
Also updates the `default-common` feature to remove the sidekiq feature. Roadster no longer suggests a particular worker backend solution as the default. Instead, consumers should enable the `worker-sidekiq` or `worker-pg` feature depending on the preferred solution.
This PR also removes the `default-diesel` feature.

chore!: Remove sidekiq and sea-orm from default features

---

src/config/service/worker/default.toml
src/worker/backend/pg/mod.rs

Currently, workers will not retry by default even though the default retry config has `max-retries = 25`. This is because there is no retry strategy nor delay provided.
This PR adds sensible defaults for the retry config. This is maybe technically a breaking change, but it can also be considered a bug fix because we want workers to retry by default with the given `max-retries = 25` default.
This PR also fixes the exponential backoff delay calculation -- before, it would always be 0 if the delay config was < 1000 and always 1 second if the delay config was >= 1000 and < 2000.
This PR also fixes the delay calcuations to use `saturating_*` methods to avoid overflows.
Closes https://github.com/roadster-rs/roadster/issues/891

fix!: Add default worker retry config values
