.github/workflows/ci.yml, .github/workflows/feature_powerset.yml
Also fix the feature powerset workflow to use nextest
=> Use fetch depth of 0 in CI

src/service/http/service.rs
https://github.com/roadster-rs/roadster/issues/95
=> Add test for the HttpService::list_routes method/cli command

Cargo.toml, justfile, src/service/worker/sidekiq/builder.rs, src/service/worker/sidekiq/mod.rs
Also add a wrapper around `sidekiq::Processor` to help with mocking.
=> Add some tests for `SidekiqWorkerServiceBuilder`

.github/workflows/ci.yml, Cargo.toml
Also, restructure CI workflow to run all checks in parallel. This _may_ reduce the overall time required to run checks on PRs.
=> Add MSRV and add CI step to validate

src/service/worker/sidekiq/builder.rs
https://github.com/roadster-rs/roadster/issues/95
=> Add tests for `remove_stale_periodic_jobs`

.github/workflows/feature_powerset.yml
In theory, this should allow the powerset workflow to run in a shorter amount of time.
=> Run separate jobs for each feature powerset check

.github/workflows/ci.yml
Closes https://github.com/roadster-rs/roadster/issues/171
=> Add semver checks to CI

.cargo-husky/hooks/pre-push, Cargo.toml, examples/minimal/Cargo.toml, examples/minimal/migration/Cargo.toml
Closes https://github.com/roadster-rs/roadster/issues/181
=> Declare minimal version of dependencies that's actually needed

src/service/worker/sidekiq/builder.rs, src/service/worker/sidekiq/mod.rs
Closes https://github.com/roadster-rs/roadster/issues/186
=> Add builder method to add middleware for the sidekiq processor

.github/workflows/conventional_commits.yml
https://www.conventionalcommits.org/en/v1.0.0/
=> ci: Add github action to verify commits follow 'Conventional Commits' format

.github/workflows/ci.yml, deny.toml
Add `cargo deny` config and add to CI.
Note: Ignore "duplicate" errors and license checks for now at least
Closes https://github.com/roadster-rs/roadster/issues/68
=> ci: Set up `cargo deny`

src/api/cli/roadster/health.rs, src/api/http/health.rs, src/config/health_check/default.toml, src/config/health_check/mod.rs, src/config/snapshots/roadster__config__app_config__tests__test.snap
Closes https://github.com/roadster-rs/roadster/issues/263
=> feat: Allow configuring the max duration of health checks

src/migration/check.rs, src/migration/schema.rs, src/migration/snapshots/roadster__migration__check__tests__str_len_gt@str_len_gt.snap, src/migration/snapshots/roadster__migration__check__tests__str_len_gte@str_len_gte.snap, src/migration/snapshots/roadster__migration__check__tests__str_not_empty@str_not_empty.snap, src/migration/snapshots/roadster__migration__schema__tests__pk_bigint_auto@pk_bigint_auto.snap, src/migration/snapshots/roadster__migration__schema__tests__pk_uuid@pk_uuid.snap, src/migration/snapshots/roadster__migration__schema__tests__pk_uuid_default@pk_uuid_default.snap, src/migration/snapshots/roadster__migration__schema__tests__pk_uuidv4@pk_uuidv4.snap, src/migration/snapshots/roadster__migration__schema__tests__pk_uuidv7@pk_uuidv7.snap, src/migration/snapshots/roadster__migration__schema__tests__table.snap, src/migration/snapshots/roadster__migration__schema__tests__timestamps@timestamps.snap, src/migration/user/tests.rs, src/testing/snapshot.rs, src/testing/snapshots/roadster__testing__snapshot__tests__description_from_thread_name@case_1.snap, src/testing/snapshots/roadster__testing__snapshot__tests__description_from_thread_name@case_2.snap, src/testing/snapshots/roadster__testing__snapshot__tests__description_from_thread_name@case_3.snap, src/testing/snapshots/roadster__testing__snapshot__tests__description_from_thread_name@case_4.snap, src/testing/snapshots/roadster__testing__snapshot__tests__description_from_thread_name@case_5.snap
Also fix a minor issue with how `TestCase` parses thread names to create a description
=> test: Add tests for schema and check helper methods

Cargo.toml, src/config/tracing/mod.rs, src/tracing/mod.rs
Also, upgrade opentelemetry dependencies
=> feat: Allow configuring the interval at which metrics are exported

README.md
This helps raise visibility of the workflow failing
=> chore: Add `Book` workflow badge to readme

Cargo.toml
Closes https://github.com/roadster-rs/roadster/issues/335
=> chore: Update sea-orm

README.md
Closes https://github.com/roadster-rs/roadster/issues/520
=> docs: Add mailpit to SMTP dev server examples

Cargo.toml, build.rs, src/lib.rs
Allows coverage task to pass for CI
=> chore: Enable nightly coverage feature

Cargo.toml, examples/leptos-0.7-ssr/Cargo.toml, examples/leptos-ssr/Cargo.toml, src/middleware/http/auth/jwt/mod.rs
Closes https://github.com/roadster-rs/roadster/issues/544
=> chore!: Upgrade Axum to 0.8 and Aide to 0.14

Cargo.toml
Closes https://github.com/roadster-rs/roadster/issues/535
=> chore!: Update bb8 to v0.9 and sidekiq-rs to 0.13.1

src/migration/collation/mod.rs, src/migration/user/m20241022_072216_case_insensitive_username_email.rs, src/service/http/middleware/size_limit.rs, src/service/http/middleware/tracing/req_res_logging.rs, src/service/worker/sidekiq/service.rs
Remove todos that we don't plan to resolve
=> chore: Remove todos

examples/full/src/api/http/example.rs, src/api/core/health.rs, src/app/context.rs
Also, add some doc comments to `AppContext` methods
=> chore!: Remove `AppContext!mailer` method in favor of the `smtp` method

Cargo.toml, src/app/context.rs
This also fixes allowing using test containers with diesel.
Closes https://github.com/roadster-rs/roadster/issues/635
=> feat: Support mysql test container

book/src/features/auth/jwt.md, book/src/features/email/index.md
Also fix a couple typos in the jwt chapter
=> docs: Write the email chapter intro

src/app/mod.rs, src/db/migration/diesel/mod.rs
Closes https://github.com/roadster-rs/roadster/issues/624
=> feat: Allow running multiple Diesel migration sources

src/health/check/mod.rs
Closes https://github.com/roadster-rs/roadster/issues/835
=> chore: Use `#[builder(with)]` for custom builder setters

src/app/context/mod.rs, src/app/context/snapshots/roadster__app__context__tests__temporary_test_db_name@case_01.snap, src/app/context/snapshots/roadster__app__context__tests__temporary_test_db_name@case_02.snap, src/app/context/snapshots/roadster__app__context__tests__temporary_test_db_name@case_03.snap, src/config/service/worker/pg/mod.rs, src/config/service/worker/pg/snapshots/roadster__config__service__worker__pg__deserialize_tests__worker_pg@case_01.snap, src/config/service/worker/pg/snapshots/roadster__config__service__worker__pg__deserialize_tests__worker_pg@case_02.snap, src/config/service/worker/pg/snapshots/roadster__config__service__worker__pg__deserialize_tests__worker_pg@case_03.snap, src/config/service/worker/pg/snapshots/roadster__config__service__worker__pg__deserialize_tests__worker_pg@case_04.snap, src/config/service/worker/snapshots/roadster__config__service__worker__deserialize_tests__deserialize_tests@case_07.snap, src/util/db/mod.rs, src/util/db/testing/diesel.rs, src/util/db/testing/mod.rs, src/util/db/testing/sea_orm.rs, src/util/db/testing/snapshots/roadster__util__db__testing__sea_orm__tests__create_database_statement.snap, src/util/db/testing/snapshots/roadster__util__db__testing__sea_orm__tests__drop_database_statement.snap, src/util/db/testing/snapshots/roadster__util__db__testing__sqlx__tests__create_database_statement.snap, src/util/db/testing/snapshots/roadster__util__db__testing__sqlx__tests__drop_database_statement.snap, src/util/db/testing/sqlx.rs
Closes https://github.com/roadster-rs/roadster/issues/841
=> fix!: Create temp test DB when only the `worker-pg` feature is enabled

.github/workflows/ci.yml, .github/workflows/feature_powerset.yml, Cargo.lock, justfile
Closes https://github.com/roadster-rs/roadster/issues/914
=> chore: Run CI checks with `--locked`
